### Base URL
@baseURL = http://localhost:5000/api
@token = {{token}}
@employeeId = {{employeeId}}
@teamId = {{teamId}}

### Health Check
GET http://localhost:5000/


### Register organisation + Admin 1
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "orgName": "NxtGen Solutions",
  "adminName": "Venkatesh Admin",
  "email": "admin@nxtGen.com",
  "password": "Venkatesh@5650"
}

### Register organisation + Admin 2
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "orgName": "Rapid Solutions",
  "adminName": "SaiPrasad Admin",
  "email": "admin@rapid.com",
  "password": "Sai@5650"
}

### Login as Admin 1
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "admin@nxtGen.com",
  "password": "Venkatesh@5650"
}

### Login as Admin 2
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "admin@rapid.com",
  "password": "Sai@5650"
}

### Logout as Admin 1
POST http://localhost:5000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ0lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjcxODQ3NjQsImV4cCI6MTc2NzIxMzU2NH0.2Xav7nfYkNJlqveF_0Y2LvK-8RteN0QEE4zJXvrPlfA



### create a manager
POST http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm9yZ0lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3Njc0MjI4NTcsImV4cCI6MTc2NzQ1MTY1N30.FZobXpDEvUrKAwGlIkD_GNnZDLLvmKtiXtAbAcIY0Bw
Content-Type: application/json

{
  "name": "Rohit Sharma",
  "email": "rohit@nxtGen.com",
  "password": "Rohit@5650",
  "role": "MANAGER"
}


### Assign manager to team by hr
POST http://localhost:5000/api/teams/3/assign-manager
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm9yZ0lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3Njc0MjI4NTcsImV4cCI6MTc2NzQ1MTY1N30.FZobXpDEvUrKAwGlIkD_GNnZDLLvmKtiXtAbAcIY0Bw
Content-Type: application/json

{
  "employeeId": 14
}


### Assign manager to team by hr
POST http://localhost:5000/api/teams/1/assign-manager
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm9yZ0lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3Njc0MjI4NTcsImV4cCI6MTc2NzQ1MTY1N30.FZobXpDEvUrKAwGlIkD_GNnZDLLvmKtiXtAbAcIY0Bw
Content-Type: application/json

{
  "employeeId": 13
}



### Get all users (Admin only)
GET http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ0lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjcxODQ3NjQsImV4cCI6MTc2NzIxMzU2NH0.2Xav7nfYkNJlqveF_0Y2LvK-8RteN0QEE4zJXvrPlfA
### View audit logs by admin
GET http://localhost:5000/api/logs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm9yZ0lkIjoxLCJyb2xlIjoiSFIiLCJpYXQiOjE3NjcyODcxNTcsImV4cCI6MTc2NzMxNTk1N30.zl7M8MJPYvZb97T4JSk0b7XtKChVEitO-aDMEhrRc4w

### Create Hr 1 by ADMIN
POST http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ0lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjcxMDI2NjcsImV4cCI6MTc2NzEzMTQ2N30.tAZwAFksc1UdNyrZUweJsV0zneKHavMrB8VTF11GFJQ
Content-Type: application/json

{
  "name": "Rahul HR",
  "email": "hr@nxtGen.com",
  "password": "Rahul@5650",
  "role": "HR"
}

### Create Hr 2 by ADMIN 
POST http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ0lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjcxMDI2NjcsImV4cCI6MTc2NzEzMTQ2N30.tAZwAFksc1UdNyrZUweJsV0zneKHavMrB8VTF11GFJQ
Content-Type: application/json

{
  "name": "Ranveer HR",
  "email": "ranveer@nxtGen.com",
  "password": "ranveer@5650",
  "role": "HR"
}

### Create Hr 2 by ADMIN 
POST http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ0lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjcxMDI2NjcsImV4cCI6MTc2NzEzMTQ2N30.tAZwAFksc1UdNyrZUweJsV0zneKHavMrB8VTF11GFJQ
Content-Type: application/json

{
  "name": "Ranveer HR",
  "email": "ranveer@nxtGen.com",
  "password": "ranveer@5650",
  "role": "HR"
}


### Getting all users by admin
GET http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ0lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjczNDkyODksImV4cCI6MTc2NzM3ODA4OX0.w32Bt7l7HBMpL-_-s6GXfKykmebl27yiFZDm3f3MyrU


### updating a hr details(user) by admin
PUT http://localhost:5000/api/users/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ0lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjczNDk2NDUsImV4cCI6MTc2NzM3ODQ0NX0.j14CUZJgQ7qTFmZipGnVXFdtj0_zOitevv4GL9xpLs4
Content-Type: application/json

{
  "name": "Ranadeesh Manager",
  "email": "ranadeesh@nxtGen.com",
  "password": "rana@5650",
  "role": "MANAGER"
}


### Login as HR
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "hr@nxtGen.com",
  "password": "Rahul@5650"
}

### role change from admin to hr
PUT http://localhost:5000/api/users/2/role
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ0lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3Njc0MjMyNTMsImV4cCI6MTc2NzQ1MjA1M30.0x-RIOqCbkpjSaf2-IEZL-Pv6V1XURr8Ju-zV6wlPJI
Content-Type: application/json

{
  "role": "HR"
}

### View audit logs by admin
GET http://localhost:5000/api/logs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ0lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjcxMDI2NjcsImV4cCI6MTc2NzEzMTQ2N30.tAZwAFksc1UdNyrZUweJsV0zneKHavMrB8VTF11GFJQ


### Login as Manager
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "mike@nxtGen.com",
  "password": "Mike@5650"
}


### Login as Manager 2
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "rohit@nxtGen.com",
  "password": "Rohit@5650"
}


### HR tries to modify ADMIN (should fail)

PUT http://localhost:5000/api/users/1/role
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm9yZ0lkIjoxLCJyb2xlIjoiSFIiLCJpYXQiOjE3NjcxMDUxODMsImV4cCI6MTc2NzEzMzk4M30.-Q-DOW5FNrXKxGXBdGavVYpHrZWqMPBj0nUGkpRN7Wg
Content-Type: application/json

{
  "role": "EMPLOYEE"
}

### Manger tries to modify ADMIN (should fail)

PUT http://localhost:5000/api/users/1/role
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm9yZ0lkIjoxLCJyb2xlIjoiTUFOQUdFUiIsImlhdCI6MTc2NzEwNTA5MiwiZXhwIjoxNzY3MTMzODkyfQ.gh50pGmHPAiuz0UcBk4WD770qqSvV8KfyJqHCJh9Mw8
Content-Type: application/json

{
  "role": "EMPLOYEE"
}


### Creating a Employee by admin(forbidden directly)
POST http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ0lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjcxMDI2NjcsImV4cCI6MTc2NzEzMTQ2N30.tAZwAFksc1UdNyrZUweJsV0zneKHavMrB8VTF11GFJQ
Content-Type: application/json

{
  "name": "suresh",
  "email": "suresh@nxtGen.com",
  "password": "Suresh@5650",
  "role": "EMPLOYEE"
}




### Promote employee to manager

PUT http://localhost:5000/api/users/8/role
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm9yZ0lkIjo2LCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjY4MDk5NDAsImV4cCI6MTc2NjgzODc0MH0.FiwXec4TLASdbpw0t1X0o0JxO3U4eG1r3tMK0uD-Emo
Content-Type: application/json

{
  "role": "MANAGER"
}


### Login as Manager promoted from employee
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "shreya@nxtGen.com",
  "password": "Shreya@5650"
}




### HR trying to delete employee (HR only):
DELETE http://localhost:5000/api/employees/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsIm9yZ0lkIjo2LCJyb2xlIjoiSFIiLCJpYXQiOjE3NjY4MTEyNTIsImV4cCI6MTc2Njg0MDA1Mn0.myTpNwug-YNWQDWvuOe5n0y-AS7q8Req8deHBZBmfPc

### Login as HR
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "hr@nxtGen.com",
  "password": "Rahul@5650"
}

### View audit logs by admin
GET http://localhost:5000/api/logs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ0lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjcxMDI2NjcsImV4cCI6MTc2NzEzMTQ2N30.tAZwAFksc1UdNyrZUweJsV0zneKHavMrB8VTF11GFJQ


### Login as Manager
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "mike@nxtGen.com",
  "password": "Mike@5650"
}


### HR creates employee approval
POST http://localhost:5000/api/approvals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm9yZ0lkIjoxLCJyb2xlIjoiSFIiLCJpYXQiOjE3NjcxMTI5OTMsImV4cCI6MTc2NzE0MTc5M30.k-uPGuKDVBCJ-AagBEjDV9hahfWJChvZzLC8x7wtRQI
Content-Type: application/json

{
  "type": "CREATE",
  "payload": {
    "first_name": "David",
    "last_name": "Smith",
    "email": "david@nxtGen.com",
    "phone": "9999999999"
  }
}

### Manager views pending
GET http://localhost:5000/api/approvals/pending
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm9yZ0lkIjoxLCJyb2xlIjoiTUFOQUdFUiIsImlhdCI6MTc2NzExMzA1MSwiZXhwIjoxNzY3MTQxODUxfQ.l76w3LbHTNHQqlgQh_fG__9Ru6qWgwiYmWybg3apZ6U


### View Audit logs by admin
GET http://localhost:5000/api/logs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ0lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjczMjgyOTUsImV4cCI6MTc2NzM1NzA5NX0.UzbWB3atZVg4nSpxHD_W82NtBygxTPOKPhupJd0QwNc




### List employees
GET http://localhost:5000/api/employees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ0lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjczMzM3MzUsImV4cCI6MTc2NzM2MjUzNX0.dXgpqS2KDWK0pSdKpFiHg0jS1U86nnqoZGnYGJjWEBo


### Get employee
GET http://localhost:5000/api/employees/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm9yZ0lkIjoxLCJyb2xlIjoiSFIiLCJpYXQiOjE3NjczMzA4OTQsImV4cCI6MTc2NzM1OTY5NH0.idCxX5k7Tk9v-i4yQ16ciyKhVzhzTH2IMCUlGY393SY


### Soft delete that employee
DELETE http://localhost:5000/api/employees/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm9yZ0lkIjo2LCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjcwMTY1MzIsImV4cCI6MTc2NzA0NTMzMn0.XDalfOYFpJ6V6yXi_8sPTF3zoxG7zjnpIszuLnSbLa4


### update  that employee
PUT http://localhost:5000/api/employees/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm9yZ0lkIjoxLCJyb2xlIjoiSFIiLCJpYXQiOjE3NjczMzA4OTQsImV4cCI6MTc2NzM1OTY5NH0.idCxX5k7Tk9v-i4yQ16ciyKhVzhzTH2IMCUlGY393SY
Content-Type: application/json

{
  "first_name": "Maanvitha",
  "last_name": "roy",
  "email": "maanvitha@company.com",
  "phone": "8080887888"

}



### List employees
GET http://localhost:5000/api/employees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm9yZ0lkIjoxLCJyb2xlIjoiSFIiLCJpYXQiOjE3NjczMzA1NTUsImV4cCI6MTc2NzM1OTM1NX0.-ediUZlwgciwGXuxGLRcPeBqdFE8RvialNCpiiS-jzc


### Approval requests check by admin
GET http://localhost:5000/api/approvals/history
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ0lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjczMjgyOTUsImV4cCI6MTc2NzM1NzA5NX0.UzbWB3atZVg4nSpxHD_W82NtBygxTPOKPhupJd0QwNc

### Analytics by Admin
GET http://localhost:5000/api/analytics
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ0lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjczNjUxODQsImV4cCI6MTc2NzM5Mzk4NH0.xYLsX3Vjpt2RcfP2LbQ2EFLRF71IzO8owrGEdi4Ryr4

### dynamic time windows by admin
GET http://localhost:5000/api/analytics?window=7d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ0lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjczNjUxODQsImV4cCI6MTc2NzM5Mzk4NH0.xYLsX3Vjpt2RcfP2LbQ2EFLRF71IzO8owrGEdi4Ryr4


### Export analytics CSV
GET http://localhost:5000/api/export/analytics
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ0lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjczNjUxODQsImV4cCI6MTc2NzM5Mzk4NH0.xYLsX3Vjpt2RcfP2LbQ2EFLRF71IzO8owrGEdi4Ryr4


### Export analytics PDF
GET http://localhost:5000/api/analytics/pdf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ0lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjczNjUxODQsImV4cCI6MTc2NzM5Mzk4NH0.xYLsX3Vjpt2RcfP2LbQ2EFLRF71IzO8owrGEdi4Ryr4

### Export Analytics PDF (ADMIN only)
GET http://localhost:5000/api/export/analytics/pdf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ0lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjczNjUxODQsImV4cCI6MTc2NzM5Mzk4NH0.xYLsX3Vjpt2RcfP2LbQ2EFLRF71IzO8owrGEdi4Ryr4
Accept: application/pdf


### Export Analytics PDF
GET http://localhost:5000/api/export/analytics/pdf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ0lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjczNjUxODQsImV4cCI6MTc2NzM5Mzk4NH0.xYLsX3Vjpt2RcfP2LbQ2EFLRF71IzO8owrGEdi4Ryr4
Accept: application/pdf

> ./analytics.pdf


### Creating a team by admin(forbidden only hr can)
POST http://localhost:5000/api/teams
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ0lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjcxMDI2NjcsImV4cCI6MTc2NzEzMTQ2N30.tAZwAFksc1UdNyrZUweJsV0zneKHavMrB8VTF11GFJQ
Content-Type: application/json

{
  "name": "Engineering",
  "description": "Product engineering team"
}


### Creating a team by hr
POST http://localhost:5000/api/teams
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm9yZ0lkIjoxLCJyb2xlIjoiSFIiLCJpYXQiOjE3NjcyNzk0NTMsImV4cCI6MTc2NzMwODI1M30._Pnsk0gaQhLD8zO-vVQF79z1tfhmw49a1bJqSHn_OGE
Content-Type: application/json

{ "name": "Frontend Engineering", "description": "UI development and client-side architecture" }

### Creating a team by hr
POST http://localhost:5000/api/teams
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm9yZ0lkIjoxLCJyb2xlIjoiSFIiLCJpYXQiOjE3NjcyNzk0NTMsImV4cCI6MTc2NzMwODI1M30._Pnsk0gaQhLD8zO-vVQF79z1tfhmw49a1bJqSHn_OGE
Content-Type: application/json

{ "name": "Customer Support", "description": "Customer queries and issue resolution" }


### updating a team by hr
PUT http://localhost:5000/api/teams/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm9yZ0lkIjoxLCJyb2xlIjoiSFIiLCJpYXQiOjE3NjczNDU3MjAsImV4cCI6MTc2NzM3NDUyMH0.hgSJ29ANsvX8tbVsXkNpr9E73foEb-VWuiSeyK08DDQ
Content-Type: application/json

{ "name": "Helpdesk Operations", "description": "First-line support and ticket resolution" }


### get a Team specific
GET http://localhost:5000/api/teams/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm9yZ0lkIjoxLCJyb2xlIjoiTUFOQUdFUiIsImlhdCI6MTc2NzQzNTI5NCwiZXhwIjoxNzY3NDY0MDk0fQ.F7HW27KcOfOVSVzPljD0ijb2FjOJZnnj1oXfKdKfy6A


### delete a Team specific
DELETE http://localhost:5000/api/teams/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm9yZ0lkIjoxLCJyb2xlIjoiTUFOQUdFUiIsImlhdCI6MTc2NzQzNTI5NCwiZXhwIjoxNzY3NDY0MDk0fQ.F7HW27KcOfOVSVzPljD0ijb2FjOJZnnj1oXfKdKfy6A



### List Teams
GET http://localhost:5000/api/teams
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm9yZ0lkIjoxLCJyb2xlIjoiTUFOQUdFUiIsImlhdCI6MTc2NzQzNTI5NCwiZXhwIjoxNzY3NDY0MDk0fQ.F7HW27KcOfOVSVzPljD0ijb2FjOJZnnj1oXfKdKfy6A


### List employees
GET http://localhost:5000/api/employees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm9yZ0lkIjoxLCJyb2xlIjoiSFIiLCJpYXQiOjE3NjczMzA1NTUsImV4cCI6MTc2NzM1OTM1NX0.-ediUZlwgciwGXuxGLRcPeBqdFE8RvialNCpiiS-jzc


### Login as Admin
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "admin@nxtGen.com",
  "password": "Venkatesh@5650"
}

###

### Get role stats (counts per role)
GET http://localhost:5000/api/org/roles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm9yZ0lkIjoxLCJyb2xlIjoiSFIiLCJpYXQiOjE3NjcxMDk4OTIsImV4cCI6MTc2NzEzODY5Mn0.CMV034OrOf4Ybhf85aaaj12Gm61VAPx7mDNVzvUXPdg

###

### List all managers(only ADMIN)
GET http://localhost:5000/api/org/managers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ0lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjcxMTI3NzAsImV4cCI6MTc2NzE0MTU3MH0.BSUkLbW3D7wAmsDXMPotIwQQ8JfonliKPWxFK9tgqMM

### List all HRs (only ADMIN)
GET http://localhost:5000/api/org/hrs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ0lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjcxMTI3NzAsImV4cCI6MTc2NzE0MTU3MH0.BSUkLbW3D7wAmsDXMPotIwQQ8JfonliKPWxFK9tgqMM





### HR requests employee creation
POST http://localhost:5000/api/approvals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm9yZ0lkIjoxLCJyb2xlIjoiSFIiLCJpYXQiOjE3NjcyNzk0NTMsImV4cCI6MTc2NzMwODI1M30._Pnsk0gaQhLD8zO-vVQF79z1tfhmw49a1bJqSHn_OGE
Content-Type: application/json

{
  "type": "CREATE",
  "payload": {
    "first_name": "Malvika",
    "last_name": "nayak",
    "email": "malvika@company.com",
    "phone": "8080887888"
  }
}


### HR requests employee creation
POST http://localhost:5000/api/approvals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm9yZ0lkIjoxLCJyb2xlIjoiSFIiLCJpYXQiOjE3NjcyNjA4MzksImV4cCI6MTc2NzI4OTYzOX0._3WiwrufVcquz4VwuxkCptMes3FXXlxfFHLg80C_ewQ
Content-Type: application/json

{
  "type": "CREATE",
  "payload": {
    "first_name": "Divakar",
    "last_name": "yadav",
    "email": "divakar@nxtGen.com",
    "phone": "8888888883"
  }
}



### Manager views pending approvals
GET http://localhost:5000/api/approvals/pending
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm9yZ0lkIjoxLCJyb2xlIjoiTUFOQUdFUiIsImlhdCI6MTc2NzI2NDc4MCwiZXhwIjoxNzY3MjkzNTgwfQ.wGTg2DksVBnZeZo37lnX48bQyYMmnwz4nDCyuG2eu0Y


### Manager approves employee creation
POST http://localhost:5000/api/approvals/16/approve-create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm9yZ0lkIjoxLCJyb2xlIjoiTUFOQUdFUiIsImlhdCI6MTc2NzI2MDc5NCwiZXhwIjoxNzY3Mjg5NTk0fQ.gfvJJf4MqSj7dyCvOzOTctYbVHkZ7iskdMVryrfX2K4


### Manager rejects employee creation
POST http://localhost:5000/api/approvals/6/reject-create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm9yZ0lkIjoxLCJyb2xlIjoiTUFOQUdFUiIsImlhdCI6MTc2NzI2NDc4MCwiZXhwIjoxNzY3MjkzNTgwfQ.wGTg2DksVBnZeZo37lnX48bQyYMmnwz4nDCyuG2eu0Y
Content-Type: application/json

{
  "reason":"employee is already in team"
}

### Reject login access by admin
POST http://localhost:5000/api/approvals/3/reject-login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ0lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjcxMTI3NzAsImV4cCI6MTc2NzE0MTU3MH0.BSUkLbW3D7wAmsDXMPotIwQQ8JfonliKPWxFK9tgqMM
Content-Type: application/json

{
  "reason": "Employee is not safe for system access"
}

### Admin views pending approvals
GET http://localhost:5000/api/approvals/pending
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ0lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjcyNjA3NDcsImV4cCI6MTc2NzI4OTU0N30.9zCGbbrQrfL-2nyRblirxA6S61zaVd_Mxu1IimSCj9E

### approve login access  by admin
POST http://localhost:5000/api/approvals/24/approve-login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ0lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjcyNjA3NDcsImV4cCI6MTc2NzI4OTU0N30.9zCGbbrQrfL-2nyRblirxA6S61zaVd_Mxu1IimSCj9E


### Employee login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "malvika@company.com",
  "password": "3ehHeGdE"
}

### Employee login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "nagesh@company.com",
  "password": "eD3sY62O"
}


### Employee login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "priyanka@company.com",
  "password": "/vQQkuhB"
}


### Employee login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "ashish@company.com",
  "password": "7TUWSe6e"
}


### Employee login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "teja@company.com",
  "password": "9u5Zr6mZ"
}




### Employee login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "tharun@company.com",
  "password": "zr9/orDE"
}


# {
#   "message": "Login created",
#   "email": "tharun@company.com",
#   "tempPassword": "zr9/orDE"
# }

### Employee login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "preetham@company.com",
  "password": "g37fa25g"
}



### Employee login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "divakar@nxtGen.com",
  "password": "jYhO9Fzw"
}


### Employee login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "barath@nxtGen.com",
  "password": "F3UKsvze"
}






### List Teams
GET http://localhost:5000/api/teams
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ0lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjcyNjA3NDcsImV4cCI6MTc2NzI4OTU0N30.9zCGbbrQrfL-2nyRblirxA6S61zaVd_Mxu1IimSCj9E



### List employees
GET http://localhost:5000/api/employees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ0lkIjoxLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjczMjgyOTUsImV4cCI6MTc2NzM1NzA5NX0.UzbWB3atZVg4nSpxHD_W82NtBygxTPOKPhupJd0QwNc



### Assign employee to team
POST http://localhost:5000/api/teams/6/assign
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm9yZ0lkIjoxLCJyb2xlIjoiSFIiLCJpYXQiOjE3NjcyODIzMTksImV4cCI6MTc2NzMxMTExOX0.Rh_YXb4atAU9F3Ty_1GOf3Ku9P0MOBW30rfYmXt-bGA
Content-Type: application/json

{
  "employeeId": 3
}

### unassign the employee from team
POST http://localhost:5000/api/teams/1/unassign
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm9yZ0lkIjoxLCJyb2xlIjoiTUFOQUdFUiIsImlhdCI6MTc2NzExMzc3MCwiZXhwIjoxNzY3MTQyNTcwfQ.bipH_fWJNVlOXR7sHicT-GAFf8xYsWHEONpy6deKwIE
Content-Type: application/json

{
  "employeeId": 2
}


### Employee login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "preetham@company.com",
  "password": "g37fa25g"
}


### Employee views profile by manager
GET http://localhost:5000/api/profile/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm9yZ0lkIjoxLCJyb2xlIjoiTUFOQUdFUiIsImlhdCI6MTc2NzQyNTEzNSwiZXhwIjoxNzY3NDUzOTM1fQ.SkRj8iaq4neIP7mhJohlTM9iLfyJUZbsiiSeCqkFmRM


### Employee views profile by manager
GET http://localhost:5000/api/profile/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE2LCJvcmdJZCI6MSwicm9sZSI6Ik1BTkFHRVIiLCJpYXQiOjE3Njc0MjUyNzMsImV4cCI6MTc2NzQ1NDA3M30.IJfp0wyYBcKPPiZdS0h51Sez7Vlm18nmNRMc2EGudcg




Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE2LCJvcmdJZCI6MSwicm9sZSI6Ik1BTkFHRVIiLCJpYXQiOjE3Njc0MjUyNzMsImV4cCI6MTc2NzQ1NDA3M30.IJfp0wyYBcKPPiZdS0h51Sez7Vlm18nmNRMc2EGudcg
### assign employee to manager


POST /api/teams/3/assign-manager
Authorization: Bearer <HR_TOKEN>
Content-Type: application/json

{
  "employeeId": 7
}
